### ISSUE TITLE
Rotiranje levo i desno

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG96-get-through#1]
Trenutno je moguce rotirati kameru levo desno samo za 90 stepeni. Napraviti fluidno pomeranje kamere levo desno.

**Comment by helenaJovanovic** [comment]
Popravljeno je okretanje dodavanjem odgovarajućih komandi i dodata je mogućnost bacanja loptice u svakom smeru uz pomoc kompozicije rotacije. Kolizija se sad određuje u odnosu na poziciju i smer uz pomoć trigonometrijskih funkcija.

Commit u pitanju je sledeći: 
https://github.com/MATF-RG19/RG96-get-through/commit/134b0a07b82411ee73dd4a6bdee231a3f378fb4f
